version: '20.10.11'
services:
  my-service:
    hostname: zthaidb.xyz
  php-apache-environment:
    container_name: php-apache
    image: php:8.0-apache
    build:
      context: ./php
      dockerfile: Dockerfile    
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80